name: Attach Debug APKs To Release

on:
  release:
    types:
      - published

jobs:
  attach-apks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package_variant: [ apt-android-7 ]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v6
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and attach APKs to release
        shell: bash
        env:
          PACKAGE_VARIANT: ${{ matrix.package_variant }}
        run: |
          RELEASE_VERSION_NAME="${GITHUB_REF/refs\/tags\//}"
          APK_DIR_PATH="./app/build/outputs/apk/debug"
          APK_VERSION_TAG="$RELEASE_VERSION_NAME+${{ matrix.package_variant }}-github-debug"
          
          export TERMUX_APK_VERSION_TAG="$APK_VERSION_TAG"
          export TERMUX_PACKAGE_VARIANT="${{ matrix.package_variant }}"
          
          chmod +x gradlew
          ./gradlew assembleDebug || true

          gh release upload "$RELEASE_VERSION_NAME" "$APK_DIR_PATH"/*.apk --clobber || true
